spring:
  cloud:
    stream:
      function:
        definition: orderCreatedEventProcessor;paymentEventProcessor
      bindings:
        orderCreatedEventProcessor-in-0:
          destination: orders
        orderCreatedEventProcessor-out-0:
          destination: payments
        paymentEventProcessor-in-0:
          destination: payments
        paymentEventProcessor-out-0:
          destination: transactions
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

server:
  port: 8881
